#!/usr/bin/env php
<?php // bin/console

// set a base path (project root)
define('BASE_PATH', __DIR__);

// require autoloading
require_once BASE_PATH . '/vendor/autoload.php';

// require the container
/** @var \Psr\Container\ContainerInterface $container */
$container = require BASE_PATH . '/config/container.php';

// Get the Console Kernel from the container
$kernel = $container->get(\Careminate\Console\Kernel::class);

// Call a handle method on the Kernel, return the console application status code
$status = $kernel->handle();

// exit with that status
exit($status);
